### ISSUE TITLE
AS014 - "Portfolio" Title on "Portfolio Tab" 

### ISSUE THREAD

**Issue by AspectiveSolution** [AspectiveSol/Aspective-Solutions-Page#8]
In a desktop scene, please make it the title at the center

**Comment by PatGomz** [comment]
Issue has been configured, please see **https://aspectivesolutions.com/portfolio/**

**Comment by PatGomz** [comment]
Issue has been configured, please see **https://aspectivesolutions.com/portfolio/**

**Comment by patgeee** [comment]
Issue has been configured, please see **https://aspectivesolutions.com/portfolio/**
